Servidor: Servidor.cpp SocketDatagrama.o PaqueteDatagrama.o 
	g++ Servidor.cpp SocketDatagrama.o PaqueteDatagrama.o -o Servidor
SocketDatagrama: SocketDatagrama.cpp PaqueteDatagrama.o SocketDatagrama.h
	g++ SocketDatagrama.cpp -c
PaqueteDatagrama: PaqueteDatagrama.cpp PaqueteDatagrama.h
	g++ PaqueteDatagrama.cpp -c
