servidor_udp: ServidorUDP.cpp SocketDatagrama.o PaqueteDatagrama.o
	g++ ServidorUDP.cpp SocketDatagrama.o PaqueteDatagrama.o -o servidor_udp
SocketDatagrama.o: SocketDatagrama.cpp PaqueteDatagrama.o SocketDatagrama.h
	g++ SocketDatagrama.cpp -c
PaqueteDatagrama.o: PaqueteDatagrama.cpp PaqueteDatagrama.h
	g++ PaqueteDatagrama.cpp -c